### ISSUE TITLE
Feature request - paranoid mode

### ISSUE THREAD

**Issue by benpye** [lukesampson/scoop#3475] opened 2019-05-20 21:10 UTC
It would be nice to have a "paranoid" mode that would prompt you to review the manifest before performing the install. Whilst the default and extras bucket should be trustworthy it gives me a bit more confidence to see exactly what's going to happen before the install.

This should probably be available as both a config value and a flag to install. I would be quite happy if all it did was open notepad with the manifest and then give you the option to continue or stop. This should also be added to update.

**Comment by Calinou** [comment] 2019-05-20 21:59
Duplicate of https://github.com/lukesampson/scoop/issues/2735.

**Closed** 2019-05-20 23:17 UTC
