### ISSUE TITLE
query: scoop export

### ISSUE THREAD

**Issue by jas99** [lukesampson/scoop#1863] opened 2017-11-23 17:52 UTC
I see one can use `scoop export` to export the state; but is thr any way to import exported file.
Similar to `brew bundle dump` which produces Brewfile that can be imported.

Thx

**Comment by r15ch13** [comment] 2017-11-23 17:53
No there is no way to import it right now. You have to create your own script to install everything from the exported list.

**Comment by rasa** [comment] 2018-03-12 17:08
Closing as a duplicate of #2105.

**Closed by rasa** 2018-03-12 17:08 UTC
