### ISSUE TITLE
'scoop update *' doesn't work in Git Bash

### ISSUE THREAD

**Issue by haobinliang** [lukesampson/scoop#3865] opened 2020-02-26 22:53 UTC
When I run 'scoop update *' in Git Bash, it prompts error below:
```
$ scoop update *
scoop update: Option -m not recognized.
```
The command works fine in PowerShell 6.

Versions:
Windows 10.0.18363 Build 18363
Git Bash 2.25.1.windows

**Comment by h404bi** [comment] 2020-02-27 03:41
wrap * with quotes in Git Bash. duplicate https://github.com/lukesampson/scoop/issues/2800

**Comment by rasa** [comment] 2020-10-20 23:12
Duplicate of #2800

**Closed by rasa** 2020-10-20 23:12 UTC
