### ISSUE TITLE
What wrong with scoop now?

### ISSUE THREAD

**Issue by Robespeler** [lukesampson/scoop#3935] opened 2020-04-21 14:51 UTC
I can't do clean install of scoop cause of 7zip blocking in Russia. Scoop wants git, git wants 7zip. And read old topics and issues here and I don't understand what should I do

Why there is no this info in documentation? The problem I suggest exists more than year
Where is solution and how other users work?
There many unanswered issues here!

Scoop is the only one! It is important

**Comment by r15ch13** [comment] 2020-04-21 15:20
Duplicate of https://github.com/lukesampson/scoop/issues/3918

**Closed by r15ch13** 2020-04-21 15:20 UTC

**Comment by dmi3mis** [comment] 2020-04-22 13:50
I had changed download link in \scoop\buckets\main\bucket\7zip.json from blocked https://7-zip.org/a/7z1900-x64.msi direct link to https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/7z1900-x64.msi
an it working now
