### ISSUE TITLE
innosetup logs Permission Denied, but still succeeds

### ISSUE THREAD

**Issue by MCOfficer** [lukesampson/scoop#3339] opened 2019-04-19 17:08 UTC
While trying to create a manifest for Celestia, i ran into this weird error:

```
Installing 'celestia' (1.6.1) [64bit]
Loading celestia-161.exe from cache
Checking hash of celestia-161.exe ... ok.
Unpacking innosetup... Move-Item : Der Zugriff auf den Pfad "C:\Users\Florian\scoop\apps\celestia\1.6.1\_scoop_unpack\{app}\locale" wurde verweigert.
In C:\Users\Florian\scoop\apps\scoop\current\lib\decompress.ps1:64 Zeichen:51
+ ... ildItem "$dir\_scoop_unpack\{app}" -r | Move-Item -dest "$dir" -force
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : WriteError: (C:\Users\Floria...ck\{app}\locale:DirectoryInfo) [Move-Item], IOException
+ FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
done.
Linking ~\scoop\apps\celestia\current => ~\scoop\apps\celestia\1.6.1
Creating shim for 'celestia'.
'celestia' (1.6.1) was installed successfully!
```
(That German part essentially translates to "Permission denied").

Despite this, the installation succeeds and as far as i can tell, no part of the `locale` folder is missing - however, all its contents are part of the app directory (`...\scoop\apps\celestia\current\`), the `locale` folder doesn't exist.

You can find the manifest version [here](https://github.com/MCOfficer/scoop-bucket/blob/bf0ba14e13f334ea63d1ba0b09f9c4aea18bf3f7/celestia.json), let me know if you need any more info.

**Comment by r15ch13** [comment] 2019-04-20 19:53
Hm, works for me:

![image](https://user-images.githubusercontent.com/432127/56461634-61f2a380-63b6-11e9-9d28-48b29f2457d6.png)


Regex tweak: `celestia-win-[^>]+>Celestia\s+([\d.]+)`

**Comment by MCOfficer** [comment] 2019-04-20 20:10
Odd. I can reproduce it on my system, even after clearing the cache. I also made sure the celestia folder has been properly removed before reinstalling, i have no idea why it's not working correctly.

i should mention that, due to a fuckup with `locate`, i can't use `scoop install` from within the powershell, i use it from cmd instead.

Also, my PS version:
```
λ» $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  590
```

**Comment by r15ch13** [comment] 2019-04-20 20:15
cmd works:
![image](https://user-images.githubusercontent.com/432127/56461835-6ff5f380-63b9-11e9-943b-d3ded11de2ad.png)


> due to a fuckup with `locate`, i can't use `scoop install` from within the powershell, i use it from cmd instead.

How did this happen? :smile:

**Comment by MCOfficer** [comment] 2019-04-21 08:39
it's not offtopic at all... but whatever:
i tried to install an mlocate port for ps, it failed and it took the ps noob that i am 2 hours to remove it. and, apparently, i didn't remove it cleanly, for scoop fails on `scoop update` and `scoop install`:

```
λ» scoop install vim
locate : Die Benennung "local:locate" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\Users\Florian\scoop\apps\scoop\current\lib\depends.ps1:25 Zeichen:38
+     $null, $manifest, $null, $null = locate $app $bucket
+                                      ~~~~~~
    + CategoryInfo          : ObjectNotFound: (local:locate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Couldn't find manifest for 'vim'.
```

---

that aside, since this bug seems to affect only me, should i PR celestia to scoop-extras?

**Comment by r15ch13** [comment] 2019-04-21 10:52
`locate` is a bad function name anyway. Will change it to `Find-Manifest` in a fix later.
Yes, please add a PR for celestia :smile:

**Comment by MCOfficer** [comment] 2019-04-23 20:29
It happened again - this time for stellarium, and this time it had consequences.
```
λ» scoop install stellarium
Installing 'stellarium' (0.19.0) [64bit]
Loading stellarium-0.19.0.1-win64.exe from cache
Checking hash of stellarium-0.19.0.1-win64.exe ... ok.
Unpacking innosetup... Move-Item : Der Zugriff auf den Pfad "C:\Users\Florian\scoop\apps\stellarium\0.19.0\_scoop_unpack\{app}\textures" wurde verweigert.
In C:\Users\Florian\scoop\apps\scoop\current\lib\decompress.ps1:64 Zeichen:51
+ ... ildItem "$dir\_scoop_unpack\{app}" -r | Move-Item -dest "$dir" -force
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Floria...\{app}\textures:DirectoryInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

done.
Linking ~\scoop\apps\stellarium\current => ~\scoop\apps\stellarium\0.19.0
Creating shim for 'stellarium'.
Creating shortcut for Stellarium (stellarium.exe)
'stellarium' (0.19.0) was installed successfully!
```

Apparently the textures are required - so much that it refuses to launch, without any error.

While looking for a logfile, i found a [innounp.log](https://gist.github.com/MCOfficer/3a19efe7ab43181c196357cb7aca89f6), which might be useful.

**Comment by niheaven** [comment] 2019-04-25 09:58
It's a failure caused by `unpack_inno`, and will be fixed in https://github.com/lukesampson/scoop/pull/3204...

**Closed** 2019-04-28 09:13 UTC

**Comment by MCOfficer** [comment] 2019-04-28 09:35
umm... i can't confirm, because now something different happens.

```
λ» scoop install pipp celestia
Couldn't find manifest for 'innounp'.

~
λ» scoop install innounp
WARN  'innounp' (0.48) is already installed.
Use 'scoop update innounp' to install a new version.


~
λ» scoop update innounp
innounp: 0.48 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

**Comment by Ash258** [comment] 2019-04-28 09:36
Run `scoop udpate` again

**Comment by MCOfficer** [comment] 2019-04-28 09:38
wow, bucket switch. did i update right in the middle of that, or do you always have to update twice?

anyways,
```
~
λ» scoop install pipp celestia
WARN  'celestia' (1.6.1) is already installed. Skipping.
Installing 'pipp' (2.5.9) [64bit]
Loading pipp_install_x64_2.5.9.zip from cache
Checking hash of pipp_install_x64_2.5.9.zip ... ok.
Extracting pipp_install_x64_2.5.9.zip ... Failed to extract files from C:\Users\Florian\scoop\apps\pipp\2.5.9\pipp_install_x64_2.5.9.zip.
Log file:
  ~\scoop\apps\pipp\2.5.9\innounp.log
```
[innounp.log](https://github.com/lukesampson/scoop/files/3124809/innounp.log)

**Comment by Ash258** [comment] 2019-04-28 09:39
It is zip file. I don't think innosetups are boundled as zips.

**Comment by Ash258** [comment] 2019-04-28 09:41
Yeah.

![A](https://i.imgur.com/Xn1jdCI.png)

You need to extract that zip file first and then do something like `installer.script = "Expand-Inno file $dir -Removal"`

**Comment by MCOfficer** [comment] 2019-04-28 09:44
uuh. you're right, although that poses like a dozen new questions for me. 

but as far as this issue is concerned, celestia and stellarium install as intended. sorry for panicking.
