### ISSUE TITLE
Sysinternals is updatable but will not be updated by scoop update

### ISSUE THREAD

**Issue by arielsalvo** [lukesampson/scoop#4142] opened 2020-10-16 14:43 UTC
Only way to know an update is available is from `scoop info`.
```
❯ scoop info sysinternals
Name: sysinternals
Description: A set of utilities to manage, diagnose, troubleshoot, and monitor a Windows environment.
Version: 2020.September.17 (Update to 2020.October.15 available)
```

It is not upgraded by `scoop update`
```
❯ scoop update sysinternals
sysinternals: 2020.September.17 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

.... and does not show in `scoop status`
```
❯ scoop status
Scoop is up to date.
These app manifests have been removed:
    station
```
I don't have another system to try.

**Comment by Ash258** [comment] 2020-10-16 14:53
Duplicate of many other issues. Relate #3721

**Comment by arielsalvo** [comment] 2020-10-16 15:43
Sorry. Didn't make the connection.
I'm subscribed to that other one.... want to close this one?

**Comment by rasa** [comment] 2020-10-20 21:57
See [https://github.com/lukesampson/scoop/issues/3812#issuecomment-569715241](https://github.com/lukesampson/scoop/issues/3812#issuecomment-569715241)

**Closed by rasa** 2020-10-20 21:57 UTC
