### ISSUE TITLE
[Suggestion] Update order

### ISSUE THREAD

**Issue by klaidliadon** [lukesampson/scoop#2762] opened 2018-11-12 16:53 UTC
I had a couple of situation where the checksum was failing and this resulted in a bad installation. 

I think that this can be improved by doing the steps in a different order:

- first download latest version and verify checksum
- then remove shims, unlink current, link new current, create shims

This should allow to keep the older version if the checksum is failing.

**Comment by Ash258** [comment] 2018-11-12 16:55
Duplicate of #1605

**Closed** 2018-11-12 20:02 UTC
