### ISSUE TITLE
Can't install any adoptopenjdk-package

### ISSUE THREAD

**Issue by nisselarsson** [lukesampson/scoop#3737] opened 2019-11-07 19:49 UTC
Regardless what adoptopenjdk-package i select for install it fails with,
```PS D:\Users\foo> scoop install adopt13-openj9-jre
Installing 'adopt13-openj9-jre' (13.0.1-9.1-0.17.0) [64bit]
Loading OpenJDK13U-jre_x64_windows_openj9_13.0.1_9_openj9-0.17.0.zip from cache
Checking hash of OpenJDK13U-jre_x64_windows_openj9_13.0.1_9_openj9-0.17.0.zip ... ok.
Extracting OpenJDK13U-jre_x64_windows_openj9_13.0.1_9_openj9-0.17.0.zip ... Exception: D:\Users\foo\scoop\apps\scoop\curren
t\lib\core.ps1
Line |
 510 |         throw "Could not find '$(fname $from)'! (error $($proc.ExitCode))"
     |         ^ Could not find 'jdk-13.0.1+9.1-jre'! (error 16)
```
The name in the "Could not find" string differs of course.

```scoop -v
Current Scoop version:
6eb90c9c (HEAD -> master, tag: 2019-10-23, origin/master, origin/HEAD) fix(update): support $persist_dir in uninstaller.scri
pt (#3692)```

**Comment by Ash258** [comment] 2019-11-07 19:54
Duplicate of ScoopInstaller/Java#98

**Comment by se35710** [comment] 2019-11-08 20:45
Can be closed. Fixed in https://github.com/ScoopInstaller/Java/pull/101

**Comment by rasa** [comment] 2020-10-20 21:37
Obsolete.

**Closed by rasa** 2020-10-20 21:37 UTC
