### ISSUE TITLE
scoop broken on pwsh 7

### ISSUE THREAD

**Issue by bernstein82** [lukesampson/scoop#3891] opened 2020-03-23 15:18 UTC
there seems to be an error in install.ps1 when running `scoop update` inside powershell 7.0.0 (the same command works in powershell 5.1.18362.628):
```powershell
~ $ scoop update *
python: 3.8.1 -> 3.8.2
Updating 1 outdated apps:
Updating 'python' (3.8.1 -> 3.8.2)
Downloading new version
Loading install-pep-514.reg from cache
Checking hash of install-pep-514.reg ... ok.

uninstall-pep-514.reg (86 B) [>                                                                               ]   0%
OperationStopped: C:\Users\ra8v\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The value must be greater than or equal to zero and less than the console's buffer size in that
     | dimension. (Parameter 'top') Actual value was 25.
```

**Comment by Ash258** [comment] 2020-03-23 16:39
Duplicate of #3886

**Comment by Ash258** [comment] 2020-03-23 16:42
Do you use some cmder profile or anything similar? I am experiencing same issue with really small files. My posh input consist of two lines in vscode and then it lead to same issue

![image](https://user-images.githubusercontent.com/13260377/77340402-8a54f180-6d2d-11ea-9bbb-fa164f80e011.png)

This will lead to lower `top` than expected and breaking dl function.

**Comment by bernstein82** [comment] 2020-03-24 09:31
nope, just using the new [windows terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab) with [powershell 7](https://github.com/PowerShell/powershell/releases)

**Comment by rasa** [comment] 2020-10-20 23:12
Duplicate of #3923

**Closed by rasa** 2020-10-20 23:12 UTC
