### ISSUE TITLE
Cooperation with Npackd

### ISSUE THREAD

**Issue by tim-lebedkov** [lukesampson/scoop#459] opened 2015-08-16 09:23 UTC
Hello,

I have a similar project called Npackd (https://github.com/tim-lebedkov/npackd , https://github.com/tim-lebedkov/npackd-cpp ) and the corresponding repository at https://npackd.appspot.com/

Are you interested in some sort of cooperation?

**Comment by kodybrown** [comment] 2015-08-18 15:50
Npackd looks really nice and well thought out! I will definitely check it out more.

As far as cooperation.. if there is something that benefits both projects, sure why not!? But, scoop uses json and Npackd uses xml files for packages. I'm not sure what we could do.. What do you have in mind?

**Comment by tim-lebedkov** [comment] 2015-08-18 16:57
well, ideally there would be only one installer, but we are far away from it so I would suggest taking small steps in this direction.

Here is what I think could be a start. I am also open for suggestions.
- add Npackd to the Scoop default bucket and vice versa
- use EXE Proxy (http://npackd.appspot.com/p/exeproxy) for shims in Scoop

BTW, the JSON/XML mismatch does not scare me much. The formats would be different anyway, even if both projects would use JSON.

**Comment by deevus** [comment] 2015-08-20 23:54
@lukesampson is away at the moment. We'll need to wait until he returns to action anything.

**Comment by tim-lebedkov** [comment] 2015-08-24 09:36
OK

**Comment by lukesampson** [comment] 2015-09-06 06:43
Thanks for getting in touch Tim.

I think it's tempting to aim for one installer that does everything, but these two projects have already established quite different goals and approaches. I think it's best for each project to focus on what we each do best.

It's not just the choice of XML/JSON. Scoop is very minimalist by design and very committed to a command-line interface, for example.

If we try to cooperate, I think we'd end up having to make a lot of compromises and it not being so much fun for either project. Happy to keep the conversation going and share ideas if you like, but at this point I don't think it's worth trying to merge the projects.

**Comment by tim-lebedkov** [comment] 2015-09-06 17:51
OK

**Closed** 2015-09-07 08:39 UTC
