### ISSUE TITLE
Problems installing rsync

### ISSUE THREAD

**Issue by kenorb** [lukesampson/scoop#2428] opened 2018-07-23 16:56 UTC
I've tried to install `rsync` but it failed, now I'm confused whether `rsync` is installed or not. Scoop reports it is, but the command is not there.

```
PS C:\Users\kenorb> scoop install rsync
Installing 'rsync' (5.7.2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://www.itefix.net/dl/cwrsync_5.7.2_x86_free.zip is not valid
PS C:\Users\kenorb> scoop install rsync
ERROR It looks like a previous installation of rsync failed.
Run 'scoop uninstall rsync' before retrying the install.
WARN  'rsync' (5.7.2) is already installed.
Use 'scoop update rsync' to install a new version.
PS C:\Users\kenorb> scoop update rsync
rsync: 5.7.2 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
PS C:\Users\kenorb> scoop list rsync
Installed apps matching 'rsync':

  rsync 5.7.2

PS C:\Users\kenorb> rsync
rsync : The term 'rsync' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ rsync
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (rsync:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\kenorb> scoop uninstall rsync
Uninstalling 'rsync' (5.7.2).
'rsync' was uninstalled.
PS C:\Users\kenorb> scoop install rsync
Installing 'rsync' (5.7.2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://www.itefix.net/dl/cwrsync_5.7.2_x86_free.zip is not valid
```

**Comment by r15ch13** [comment] 2018-07-23 18:04
Duplicate of https://github.com/lukesampson/scoop/issues/2295

**Closed by r15ch13** 2018-07-23 18:04 UTC
