### ISSUE TITLE
Bash shims fail to run if scoop is installed in a paths with spaces

### ISSUE THREAD

**Issue by nickhutchinson** [lukesampson/scoop#4096] opened 2020-08-22 00:09 UTC
The bash shims scoop creates for powershell scripts don't work if scoop is installed into a path with spaces. For example, here's the contents of my `C:\Users\Nick Hutchinson\scoop\apps\scoop\shims\scoop`:

```
#!/bin/sh
powershell.exe -noprofile -ex unrestricted "C:\Users\Nick Hutchinson\scoop\apps\scoop\current\bin\scoop.ps1"  "$@"
```

Running `scoop` in a git-bash shell fails with the following error:
```
Program 'Nick' failed to run: No application is associated with the specified file for this operationAt line:1 char:1
+ C:\Users\Nick Hutchinson\scoop\apps\scoop\current\bin\scoop.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ C:\Users\Nick Hutchinson\scoop\apps\scoop\current\bin\scoop.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by rasa** [comment] 2020-10-20 23:13
Duplicate of #3878

**Closed by rasa** 2020-10-20 23:13 UTC
