### ISSUE TITLE
Reset command reverts the direction of symlinks

### ISSUE THREAD

**Issue by kimbirkelund** [lukesampson/scoop#2828] opened 2018-12-01 14:50 UTC
It appears that after running reset once on an installed app the symlink is from the persist folder to the app and not the other way around. 

Using rufus as an example (I've seen it with multiple apps) the following occurs.

1. Uninstall rufus and delete persist folder
2. Install rufus
    - Rufus is installed and persist folder contains rufus.ini and a folder rufus_files
3. Run scoop reset rufus
    - Command runs successfully
    - Persist folder now contains the same
4. Run scoop reset rufus again
    - Command runs successfully but writes "Cannot create a file when that file already exists."
    - Persist now contains rufus.ini and folder rufus_files as before, but rufus_files now contains a junction named rufus_files that points back to its parent (i.e. the rufus_files folder that was there already)
5. Run scoop reset rufus again
    - Command fails with error: "Cannot create a file when that file already exists."
    - Persist folder is unchanged

The behavior it quite new and might very well coincide with PR #2773. However looking at the change in there and how `persist_data` is used elsewhere I cannot explain why the error would occur.

I've attached a transcript of my reproduction.

[repro.txt](https://github.com/lukesampson/scoop/files/2635960/repro.txt)

**Comment by Ash258** [comment] 2018-12-01 14:52
Duplicate of #2724

Should be fixed with #2774

**Comment by kimbirkelund** [comment] 2018-12-01 14:59
Seems about right :)

**Comment by kimbirkelund** [comment] 2018-12-01 15:00
But is there a timeframe?

**Closed** 2018-12-06 00:12 UTC
