### ISSUE TITLE
Installing older versions of packages doesn't work

### ISSUE THREAD

**Issue by viktorbard** [lukesampson/scoop#4993] opened 2022-06-17 12:10 UTC
#### Current Behavior
When trying to install older versions of packages it instead installs latest version.

#### Expected Behavior
The stated version should be installed

#### Additional context/output
```
❯ scoop install terraform@1.1.3
WARN  Given version (1.1.3) does not match manifest (1.2.3)
WARN  Attempting to generate manifest for '/terraform' (1.1.3)
Autoupdating /terraform
Searching hash for terraform_1.1.3_windows_386.zip in https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_SHA256SUMS
Found: e9c41f7141ae511f05e13067ccac4158d78a1214d535d0bda4a549529d4ef0e3 using Extract Mode
Searching hash for terraform_1.1.3_windows_amd64.zip in https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_SHA256SUMS
Found: b2890c05c04cfa3cad3c3d5316e6670b963a347ad42ba02fede55268148bce5a using Extract Mode
Writing updated /terraform manifest
Installing 'terraform' (1.2.3) [64bit]
terraform_1.2.3_windows_amd64.zip (19,1 MB) [==========================================================================================================================================================] 100%
Checking hash of terraform_1.2.3_windows_amd64.zip ... ok.
Extracting terraform_1.2.3_windows_amd64.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\terraform\current => ~\scoop\apps\terraform\1.2.3
Creating shim for 'terraform'.
'terraform' (1.2.3) was installed successfully!
```

```
❯ scoop install nodejs@16.9.1
WARN  Given version (16.9.1) does not match manifest (18.4.0)
WARN  Attempting to generate manifest for '/nodejs' (16.9.1)
Autoupdating /nodejs
Searching hash for node-v16.9.1-win-x64.7z in https://nodejs.org/dist/v16.9.1/SHASUMS256.txt.asc
Found: 83c4dc9b6478fd065d0fdce0f4d578de0b24bd54b2f85f8970b3f2dce870c9cc using Extract Mode
Writing updated /nodejs manifest
Installing 'nodejs' (18.4.0) [64bit]
Loading node-v18.4.0-win-x64.7z from cache
Checking hash of node-v18.4.0-win-x64.7z ... ok.
Extracting node-v18.4.0-win-x64.7z ... done.
Linking ~\scoop\apps\nodejs\current => ~\scoop\apps\nodejs\18.4.0
Persisting bin
Persisting cache
Running post_install script...
'nodejs' (18.4.0) was installed successfully!
```

#### Possible Solution
I noticed that `scoop download <package>@<version>` correctly downloads the package to the cache so either be able do install from cache or fix `scoop install <package>@<version>` to acutally install `<version>`

### System details

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** 7.2.4

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-06-17T14:08:26.0104318+02:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment] 2022-06-17 12:14
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4984

**Closed as completed by rashil2000** 2022-06-17 12:14 UTC
Labels: bug
