### ISSUE TITLE
move to use symlinks and not copy the exe/dll files

### ISSUE THREAD

**Issue by isamuelson** [lukesampson/scoop#732] opened 2016-03-09 13:54 UTC

**Comment by rivy** [comment] 2016-03-09 15:20
In a brain-dead decision, Win7+, by default, only grants the ability to create symlinks to administrators (ref: http://superuser.com/questions/124679/how-do-i-create-a-link-in-windows-7-home-premium-as-a-regular-user/125981#125981 [<kbd>@@</kbd>](https://archive.is/3vF2y) )  will not allow creation of symlinks without administrator privileges. The specifically required privilege is "SeCreateSymbolicLinkPrivilege". So, using symlinks isn't possible within the guidelines of the tool, i.e. installing without requiring admin privileges.

Oddly, junctions can be created with the default normal user permissions, but I don't see that as being helpful.

**Comment by isamuelson** [comment] 2016-03-23 18:26
the issue that i'm having is that some of the packages, install multiple executables and those require some dll files...it seems that only copy the executables isn't enough

**Comment by lukesampson** [comment] 2016-03-23 22:40
It's kind of a feature of scoop that installs are self-contained. This helps avoid the problems that come with shared dependencies, like incompatible versions and missing components caused by uninstalling something that other programs need.

Quite a few manifests (e.g. [OpenSSH](https://github.com/lukesampson/scoop/blob/master/bucket/openssh.json)) install their own copies of DLLs, even if they're already installed elsewhere for other programs.

Would the approach or downloading multiple files like OpenSSH work for you?

**Comment by isamuelson** [comment] 2016-03-24 21:34
I wouldn't mind that.

I can be specific around the problem i'm having

ConENU package and git... the ConENU bash does not recognize git or the
configuration files.

I'm in the process of rebuilding my windows box, I will try to send you a
proper issue by end of week

On Wed, Mar 23, 2016 at 6:40 PM, Luke Sampson <notifications@github.com>
wrote:

> It's kind of a feature of scoop that installs are self-contained. This
> helps avoid the problems that come with shared dependencies, like
> incompatible versions and missing components caused by uninstalling
> something that other programs need.
>
> Quite a few manifests (e.g. OpenSSH
> <https://github.com/lukesampson/scoop/blob/master/bucket/openssh.json>)
> install their own copies of DLLs, even if they're already installed
> elsewhere for other programs.
>
> Would the approach or downloading multiple files like OpenSSH work for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lukesampson/scoop/issues/732#issuecomment-200571500>
>



-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by lukesampson** [comment] 2016-03-24 21:42
Does [this](https://github.com/lukesampson/scoop-extras/blob/master/conemu.json) help? You need to run `scoop bucket add extras; scoop install conemu` to install this—it's in the [extras](https://github.com/lukesampson/scoop-extras) bucket rather than the main bucket because it's considered a GUI program.

**Comment by isamuelson** [comment] 2016-03-24 22:34
fresh install

1. iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
2. scoop install git
( the git-bash command is not available ...)
3. scoop bucket add extras
4. scoop install conemu

problems:

1. conemu does not detect bash ( i will try to make a pull request for that
this weekend, it seems that simply copy the git-bash.exe to the shims
folder made it work)
2. would it be possible to add a scoop folder for the start up menu and
provide shortcuts? (i might be able to help with that as well )


On Thu, Mar 24, 2016 at 5:42 PM, Luke Sampson <notifications@github.com>
wrote:

> Does this
> <https://github.com/lukesampson/scoop-extras/blob/master/conemu.json>
> help? You need to run scoop bucket add extras; scoop install conemu to
> install this—it's in the extras
> <https://github.com/lukesampson/scoop-extras> bucket rather than the main
> bucket because it's considered a GUI program.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lukesampson/scoop/issues/732#issuecomment-201037861>
>



-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by lukesampson** [comment] 2016-03-24 22:52
1. It might be better to add git-bash.json as a separate manifest in extras, as not everyone who wants conemu will want bash. If conemu detects git-bash.exe on the path without any extra config, then it should work fine as a separate manifest.
2. Yes you can add start menu shortcuts that end up under "Scoop Apps". See #678.

**Comment by isamuelson** [comment] 2016-03-25 00:09
git-bash.exe and bash.exe comes with the git package
under ~\AppData\Local\scoop\apps\git\2.7.1.windows.2\...

On Thu, Mar 24, 2016 at 6:52 PM, Luke Sampson <notifications@github.com>
wrote:

>
>    1. It might be better to add git-bash.json as a separate manifest in
>    extras, as not everyone who wants conemu will want bash. If conemu detects
>    git-bash.exe on the path without any extra config, then it should work fine
>    as a separate manifest.
>    2. Yes you can add start menu shortcuts that end up under "Scoop
>    Apps". See #678 <https://github.com/lukesampson/scoop/issues/678>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lukesampson/scoop/issues/732#issuecomment-201063961>
>



-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by isamuelson** [comment] 2016-03-25 00:10
sorry, sent too early...

copy both executables to the shims dir i get this error:

Skipping command-line
'"C:\Users\ido\AppData\Local\scoop\shims\..\usr\bin\bash.exe"'
('C:\Users\ido\AppData\Local\scoop\shims\..\usr\bin\bash.exe' not found)
Need a valid command-line; Edit the string resources accordingly

On Thu, Mar 24, 2016 at 8:09 PM, Ido Samuelson <ido.samuelson@gmail.com>
wrote:

> git-bash.exe and bash.exe comes with the git package
> under ~\AppData\Local\scoop\apps\git\2.7.1.windows.2\...
>
> On Thu, Mar 24, 2016 at 6:52 PM, Luke Sampson <notifications@github.com>
> wrote:
>
>>
>>    1. It might be better to add git-bash.json as a separate manifest in
>>    extras, as not everyone who wants conemu will want bash. If conemu detects
>>    git-bash.exe on the path without any extra config, then it should work fine
>>    as a separate manifest.
>>    2. Yes you can add start menu shortcuts that end up under "Scoop
>>    Apps". See #678 <https://github.com/lukesampson/scoop/issues/678>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/lukesampson/scoop/issues/732#issuecomment-201063961>
>>
>
>
>
> --
>
> *Ido Samuelson*
>
> Phone (US): +1-415-562-8582
>
> Email: *ido.samuelson@gmail.com*
> LinkedIn: http://www.linkedin.com/in/isamuelson
>
> Skype: ido_samuelson
>



-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by isamuelson** [comment] 2016-03-25 00:34
I found out when conemu will detect bash as a shell.

it is when i'm running conemu from the following folder:

C:\Users\ido\AppData\Local\scoop\apps\git\2.7.1.windows.2\bin>conemu



On Thu, Mar 24, 2016 at 8:10 PM, Ido Samuelson <ido.samuelson@gmail.com>
wrote:

> sorry, sent too early...
>
> copy both executables to the shims dir i get this error:
>
> Skipping command-line
> '"C:\Users\ido\AppData\Local\scoop\shims\..\usr\bin\bash.exe"'
> ('C:\Users\ido\AppData\Local\scoop\shims\..\usr\bin\bash.exe' not found)
> Need a valid command-line; Edit the string resources accordingly
>
> On Thu, Mar 24, 2016 at 8:09 PM, Ido Samuelson <ido.samuelson@gmail.com>
> wrote:
>
>> git-bash.exe and bash.exe comes with the git package
>> under ~\AppData\Local\scoop\apps\git\2.7.1.windows.2\...
>>
>> On Thu, Mar 24, 2016 at 6:52 PM, Luke Sampson <notifications@github.com>
>> wrote:
>>
>>>
>>>    1. It might be better to add git-bash.json as a separate manifest in
>>>    extras, as not everyone who wants conemu will want bash. If conemu detects
>>>    git-bash.exe on the path without any extra config, then it should work fine
>>>    as a separate manifest.
>>>    2. Yes you can add start menu shortcuts that end up under "Scoop
>>>    Apps". See #678 <https://github.com/lukesampson/scoop/issues/678>.
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/lukesampson/scoop/issues/732#issuecomment-201063961>
>>>
>>
>>
>>
>> --
>>
>> *Ido Samuelson*
>>
>> Phone (US): +1-415-562-8582
>>
>> Email: *ido.samuelson@gmail.com*
>> LinkedIn: http://www.linkedin.com/in/isamuelson
>>
>> Skype: ido_samuelson
>>
>
>
>
> --
>
> *Ido Samuelson*
>
> Phone (US): +1-415-562-8582
>
> Email: *ido.samuelson@gmail.com*
> LinkedIn: http://www.linkedin.com/in/isamuelson
>
> Skype: ido_samuelson
>



-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by lukesampson** [comment] 2016-06-01 00:59
Going back to the original issue, I'll close this because I think we have to stick with shims as the best option.

As @rivy mentioned, junctions and hard links might be possible without admin permissions. But I think there are other problems with these approaches. Hard links lead to problems with the exe thinking it is executing in the directory of the link, not the actual directory. Directory junctions might be useful for shared config, but not for the executables as we'd need to add the directories to %PATH%, and we're trying to avoid that.

**Closed by lukesampson** 2016-06-01 00:59 UTC

**Comment by specular-scullion** [comment] 2023-08-31 04:37
you can at least hardlink the shims instead of making multiple copies of the same 123.5k file :)
It will also save disk i/o when executing shims, since it will have to be only read once.

Though, if there is currently an active process started from any of the hardlinked shims, Windows will not allow deleting the exe.
But It can be "moved" to another hardlink location (`move shims\terraform-docs.exe shims\terraform.exe`) which will have the removal effect without overwrite prompt (same principle works with WinAPI, not just the shell).
