### ISSUE TITLE
Java or JDK 9

### ISSUE THREAD

**Issue by b-palaniappan** [lukesampson/scoop#1954] opened 2018-01-15 03:11 UTC
Is there a plan to add Java 9 in Scoop bucket ?

**Comment by rasa** [comment] 2018-01-15 07:27
See https://github.com/lukesampson/scoop-extras/pull/576

**Comment by rasa** [comment] 2018-03-12 00:40
Duplicate of https://github.com/lukesampson/scoop-extras/pull/576

**Closed by rasa** 2018-03-12 00:40 UTC
Labels: duplicate
