### ISSUE TITLE
Can someone add TortoiseGit?

### ISSUE THREAD

**Issue by vsDizzy** [lukesampson/scoop#2665] opened 2018-10-12 00:00 UTC
I wonder why is this still not added.

**Comment by Calinou** [comment] 2018-10-12 07:40
This issue should be opened on [scoop-extras](https://github.com/lukesampson/scoop-extras/issues), since TortoiseGit is a graphical application and only command-line applications can be added to the main bucket.

You could also take a look at writing an [app manifest](https://github.com/lukesampson/scoop/wiki/App-Manifests) for TortoiseGit :slightly_smiling_face:

**Comment by h404bi** [comment] 2018-10-13 15:36
To see if anyone could complete the manifest.
```json
{
    "homepage": "https://tortoisegit.org/",
    "description": "Windows Shell Interface to Git",
    "license": "GPL-2.0-only",
    "version": "2.7.0",
    "architecture": {
        "64bit": {
            "url": "https://download.tortoisegit.org/tgit/2.7.0.0/TortoiseGit-2.7.0.0-64bit.msi",
            "hash": "ea4d68423484143de7c2afe75d28eed29ecb695e3b4ad41c47d8365fe70c76bd"
        },
        "32bit": {
            "url": "https://download.tortoisegit.org/tgit/2.7.0.0/TortoiseGit-2.7.0.0-32bit.msi",
            "hash": "5c9c734cd5b354f5fdd485793677430a067a629f5019410d65a31e3306a81470"
        }
    },
    "extract_dir": "Program Files\\TortoiseGit",
    "checkver": {
        "url": "https://tortoisegit.org/download/",
        "re": "The current stable version is: ([\\d.]+)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://download.tortoisegit.org/tgit/$version.0/TortoiseGit-$version.0-64bit.msi"
            },
            "32bit": {
                "url": "https://download.tortoisegit.org/tgit/$version.0/TortoiseGit-$version.0-32bit.msi"
            }
        }
    }
}
```

**Comment by onacit** [comment] 2020-03-03 06:29
My newly installed TortoiseGit doesn't work with `C:\Users\onacit\scoop\shims` for `Git.exe Path:`.

Can anybody help?

**Comment by NNNNNNAAAAAA** [comment] 2020-03-16 19:08
> 我新安装的TortoiseGit不适`C:\Users\onacit\scoop\shims`用于for `Git.exe Path:`。
> 
> 有人可以帮忙吗？

You can use this path
C:\Users\onacit\scoop\apps\git\current\bin\git.exe

**Comment by onacit** [comment] 2020-04-06 04:54
@NNNNNNAAAAAA 你好. It seems work.

**Comment by rasa** [comment] 2020-10-20 02:23
Duplicate of https://github.com/lukesampson/scoop-extras/issues/1435

**Closed by rasa** 2020-10-20 02:23 UTC
Labels: help wanted

**Comment by haussmann** [comment] 2026-01-15 06:18
Than you for your request, please take a look at `nonportable/tortoisegit-np`.
