### ISSUE TITLE
[Urgently!] Problem...

### ISSUE THREAD

**Issue by vanja-san** [lukesampson/scoop#3374] opened 2019-04-25 05:03 UTC
In our country blocked the site 7zip, please make an alternative download link!
**For example:**  `https://sourceforge.net/projects/sevenzip/files/7-Zip/`

_Screenshot (**In Russian it is written:** Unable to connect to remote server):_
![2019-04-25-11-58-00](https://user-images.githubusercontent.com/7201687/56710646-68d03c00-6751-11e9-894f-53c1fc310ead.png)

> SORRY FOR MY BAD ENGLISH!

**Comment by Ash258** [comment] 2019-04-25 05:26
Duplicate of #3287

**Closed** 2019-04-28 09:13 UTC
