### ISSUE TITLE
7zip@19.00: extract_dir error

### ISSUE THREAD

**Issue by loong95** [lukesampson/scoop#3388] opened 2019-04-26 01:55 UTC
```
Installing '7zip' (19.00) [64bit]
Loading 7z1900-x64.msi from cache
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... ERROR Could not find '7-Zip'! (error 16)
```

**Comment by niheaven** [comment] 2019-04-26 07:06
ref: https://github.com/lukesampson/scoop/issues/3198#issuecomment-470772222

This may be caused by `lessmsi`, and will be fixed in https://github.com/lukesampson/scoop/pull/3204

**Closed** 2019-04-28 09:13 UTC
