### ISSUE TITLE
ripgrep@12.0.0 recommends extras/vcredist2015, but won't work without it

### ISSUE THREAD

**Issue by vvuk** [lukesampson/scoop#3903] opened 2020-03-29 02:17 UTC
Installing ripgrep@12.0.0:

```
PS C:\Users\vladimir> scoop install ripgrep
Installing 'ripgrep' (12.0.0) [64bit]
Checking hash of ripgrep-12.0.0-x86_64-pc-windows-msvc.zip ... ok.
Extracting ripgrep-12.0.0-x86_64-pc-windows-msvc.zip ... done.
Linking ~\scoop\apps\ripgrep\current => ~\scoop\apps\ripgrep\12.0.0
Creating shim for 'rg'.
'ripgrep' (12.0.0) was installed successfully!
'ripgrep' suggests installing 'extras/vcredist2015'.
PS C:\Users\vladimir> rg
PS C:\Users\vladimir>
```

note that rg just silently exits.  If I install `extras/vcredist2015`, then rg works.

I guess I may have had the redist installed some other way, but asking users to install it via scoop so that scoop knows it's installed seems worthwhile; if I hadn't had an idea of what was wrong, I would think that the tool was just broken somehow.

**Comment by linsui** [comment] 2020-03-29 02:55
See https://github.com/lukesampson/scoop/issues/3360

**Comment by Calinou** [comment] 2020-03-29 12:16
There's a 64-bit ripgrep Windows binary that uses the GNU ABI available in the [current latest release](https://github.com/BurntSushi/ripgrep/releases/tag/12.0.0). Maybe we should use it for the 64-bit download so it can run without any dependencies?

**Comment by joshk0** [comment] 2020-05-09 15:49
This was the same for openssl. Would it be reasonable to depend on the vcredist to use scoop at all since it's so commonly relied upon?

**Comment by Calinou** [comment] 2020-05-09 16:57
@joshk0 Unfortunately, there are a lot of incompatible vcredist versions out there. If you want to run all Windows applications, you'll need to install all of them, in both 64-bit and 32-bit variants.

**Comment by joshk0** [comment] 2020-05-09 18:43
Got it, thanks @Calinou . That sounds like the best approach is #3360, make scoop aware of MSI database so that it can know install vcredists specific versions which are required by specific scoop bucket entries.

**Comment by rasa** [comment] 2020-10-20 23:12
Duplicate of #3360

**Closed by rasa** 2020-10-20 23:12 UTC
