### ISSUE TITLE
openssh@7.6p1: hash check failed

### ISSUE THREAD

**Issue by amreltahan** [lukesampson/scoop#2437] opened 2018-07-25 09:21 UTC
Checking hash of icu-59.1-1-x86_64.pkg.tar.xz... ERROR Hash check failed!
App:         openssh
URL:         http://repo.msys2.org/msys/x86_64/icu-59.1-1-x86_64.pkg.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    d64bbf81b569b322f428cc4a18071991abca4b0d56c2ec2ce74052348d2b2e7a
Actual:      4df6b0b50a0afbc4eeeae9d8df363d41c788ca49be6f8c60a753948652c10e24

Please create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=openssh%407.6p1%3a+hash+check+failed

**Comment by r15ch13** [comment] 2018-07-25 14:55
Duplicate of https://github.com/lukesampson/scoop/issues/2388
Discussed in https://github.com/lukesampson/scoop/issues/2414

**Closed by r15ch13** 2018-07-25 14:55 UTC
