### ISSUE TITLE
Scoop does not find binaries from Yarn

### ISSUE THREAD

**Issue by DanielRuf** [lukesampson/scoop#3103] opened 2019-02-09 22:13 UTC
```
$ yarn global add DanielRuf/phantomjs-mocked
yarn global v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "phantomjs-mocked@1.0.0" with binaries:
      - phantomjs
Done in 19.10s.

Daniel@Daniel-MSI MINGW64 ~/scoop/apps/scoop/current (master)
$ phantomjs
/bin/sh: /c/Users/Daniel/scoop/apps/yarn/current/bin/../../../../../AppData/Local/Yarn/Data/global/node_modules/.bin/phantomjs: No such file or directory
```

While `/c/Users/Daniel/AppData/Local/Yarn/Data/global/node_modules/.bin/phantomjs` works.
But one thing is weird. `pwd` shows me that `/c/Users/Daniel/scoop/apps/yarn/current/bin/../../../../../` is `/c/Users/Daniel` but ll shows a different path.

```
ll /c/Users/Daniel/scoop/apps/yarn/current/bin/../../../../../
total 65
lrwxrwxrwx 1 Daniel 197121  14 Apr 12  2018 'All Users' -> /c/ProgramData/
drwxr-xr-x 1 Daniel 197121   0 Feb  9 19:21  Daniel/
drwxr-xr-x 1 Daniel 197121   0 Mai  6  2018  Default/
lrwxrwxrwx 1 Daniel 197121  16 Apr 12  2018 'Default User' -> /c/Users/Default/
drwxr-xr-x 1 Daniel 197121   0 Okt 10  2016  Default.migrated/
drwxr-xr-x 1 Daniel 197121   0 Mai  6  2018  DefaultAppPool/
-rw-r--r-- 1 Daniel 197121 174 Apr 12  2018  desktop.ini
drwxr-xr-x 1 Daniel 197121   0 Mai  6  2018  Public/
```

So there is something very wrong.

**Comment by DanielRuf** [comment] 2019-02-09 22:14
Also when I remove the package again with `yarn global remove phantomjs-mocked`, it is not deleted in the bin directory of scoop but in the bin directory of Yarn.

**Comment by r15ch13** [comment] 2019-02-09 22:18
Duplicate of https://github.com/lukesampson/scoop/issues/1641

**Comment by DanielRuf** [comment] 2019-02-09 22:22
Yep, checked other binaries now and Yarn generated a different content. But still weird that the other binary is not deleted and that there are two different ones.

**Closed** 2019-02-09 22:21 UTC

**Comment by DanielRuf** [comment] 2019-02-09 22:23
But still weird that the other binary is not deleted and that there are two different ones.
