### ISSUE TITLE
Feature request: Fish Shell

### ISSUE THREAD

**Issue by lucianmarin** [lukesampson/scoop#3937] opened 2020-04-22 20:00 UTC
```
scoop install fish
```

Pretty please! Cygwin version is a nightmare!

**Comment by Ash258** [comment] 2020-04-22 20:29
Will not be implemented

Duplicate of ScoopInstaller/Main#903

**Comment by rasa** [comment] 2020-10-20 23:13
Duplicate of ScoopInstaller/Main#903

**Closed by rasa** 2020-10-20 23:13 UTC
