### ISSUE TITLE
[Request] Add Crystal-lang

### ISSUE THREAD

**Issue by rishavs** [lukesampson/scoop#4114] opened 2020-09-14 08:21 UTC
Crystal is a programming language with the following goals:

- Have a syntax similar to Ruby (but compatibility with it is not a goal).
- Be statically type-checked, but without having to specify the type of variables or method arguments.
- Be able to call C code by writing bindings to it in Crystal.
- Have compile-time evaluation and generation of code, to avoid boilerplate code.
- Compile to efficient native code.

site: https://crystal-lang.org/

It has a Github Actions CI which produces the windows binaries https://github.com/crystal-lang/crystal/actions?query=workflow%3A%22Windows+CI%22

While parts of language (like networking) are still under work, a lot of if it usable today, specifically for things like gamedev and shell programs. Ref https://pryp.in/blog/28/running-crystal-natively-on-windows-building-videogame-examples.html

I hope that if we can have scoop support for fetching Crystal binaries, setting up the required env vars and the folder structure for the compiler, it would remove a lot of friction in getting starting on this wonderful language.

**Comment by linsui** [comment] 2020-09-15 14:38
You need to file this request in the Main repo. https://github.com/ScoopInstaller/Main Since Windows is not officially supported, it's a little out of the scope of Scoop.

**Comment by rasa** [comment] 2020-10-20 23:13
Duplicate of #3775

**Closed by rasa** 2020-10-20 23:13 UTC
