### ISSUE TITLE
Issue when using scoop update from a manifest url

### ISSUE THREAD

**Issue by stephanec1** [lukesampson/scoop#3683] opened 2019-10-13 19:59 UTC
**What:**
We can install an application from a local manifest (url), we should be able to update it from the same url

**Use case:**
1. Create an application manifest on your machine `C:/scoop_manifests/appA.json`
2. install an app from the local manifest on your machine:
`scoop install C:/scoop_manifests/appA.json`
3. Update the local manifest `C:/scoop_manifests/appA.json`
4. Update the app with scoop
`scoop update appA`

**Expected:**
This should update the app with your new manifest value

**Actual result:**
Scoop look in its buckets if the app exist, if so it update the app to its latest bucket version

**Investigation:**
in scoop-update.ps1 we don't concider if the manifest contains an url instead of an bucket name

**Comment by Ash258** [comment] 2019-10-13 20:00
Duplicate of #3607

**Comment by stephanec1** [comment] 2019-10-13 20:05
The fix could be implemented in the `function update` of `scoop-update.ps1`
The updated json manifest is well detected, the only issue is to not concider that the app was installed through an url when `install_app` is called at the end of the function. We are just doing 
`install_app $app $architecture $global $suggested $use_cache $check_hash`
where `$app` is the name of the app and not its url reference

**Closed** 2019-10-18 12:04 UTC
