### ISSUE TITLE
Downloading a small file causes an error in the progress bar function

### ISSUE THREAD

**Issue by thorstenkampe** [lukesampson/scoop#3923] opened 2020-04-09 17:19 UTC
Ssh to to Windows 2019 server core from Windows 10 with KiTTY (a popular PuTTY clone):
```
> scoop install python
Installing 'python' (3.8.2) [64bit]
install-pep-514.reg (555 B) [=================================================================================================================] 100%
Checking hash of install-pep-514.reg ... ok.

uninstall-pep-514.reg (86 B) [>                                                                                                               ]   0%
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 43.
URL https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/python/uninstall-pep-514.reg is not valid
```

Installing via RDP works fine. All components current versions. Using PowerShell Desktop 5.1 .17763 .1007 on server.

**Comment by grrttedwards** [comment] 2020-04-19 19:33
I am experiencing this but on a fresh install of Windows 10, directly in a local powershell 7 console.

```
PS C:\Users\Garrett> scoop install python
Installing 'python' (3.8.2) [64bit]
Loading install-pep-514.reg from cache
Checking hash of install-pep-514.reg ... ok.

uninstall-pep-514.reg (86 B) [>                                                                                                           ]   0%
The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 43.
URL https://raw.githubusercontent.com/ScoopInstaller/Main/master/scripts/python/uninstall-pep-514.reg is not valid
```

**Comment by r15ch13** [comment] 2020-04-19 19:57
This is caused by the small filesize of `uninstall-pep-514.reg` and the progress bar function.
As a workaround, you could install `aria2` to bypass scoops progress bar. (`scoop install aria2`)

---
The bug is caused by setting the top cursor position to an invalid location.
https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/install.ps1#L471

It could be fixed by either removing the `+ 1` part or checking the value and resetting it.
```pwsh
$top = $top + 1
if($top -gt $console.CursorPosition.Y) {
    $top = $console.CursorPosition.Y
}
```

**Comment by grrttedwards** [comment] 2020-04-19 20:06
Awesome, thank you. @r15ch13 
Also tagging #3891

**Closed** 2020-05-14 17:39 UTC
Labels: bug
