### ISSUE TITLE
GNU Make Downlod is Broken

### ISSUE THREAD

**Issue by Fleshgrinder** [lukesampson/scoop#2076] opened 2018-03-02 09:43 UTC
[`scoop install make`](https://github.com/lukesampson/scoop/blob/master/bucket/make.json) fails on all my Windows machines. I cannot tell what the issue is, sorry.

```
scoop install make
Installing 'make' (4.2) [64bit]
The remote server returned an error: 227 Entering Passive Mode (108,36,217,27,91,67)
.
URL ftp://ftp.equation.com/make/64/make.exe is not valid
```

The URL `ftp://ftp.equation.com/make/64/` is valid and reachable.

Scoop thinks that it was installed and one has to issue `scoop uninstall make` to get rid of the wrong state.

**Comment by r15ch13** [comment] 2018-03-02 17:23
It asks for a username/password when I try it in Firefox. Using anonymous/asd@asd.de as credentials works but it says there are more than 200 users logged in. 🤷‍♂️

**Comment by Fleshgrinder** [comment] 2018-03-02 18:28
Interesting, it wasn't asking me when I created the issue today but now it does.

**Comment by excitoon** [comment] 2018-03-02 19:01
I would suggest using only popular or reliable file servers like github, sourcefourge (well, better not). In case when it is absolutely impossible to find good source I would just make a release on github and upload files there.

**Comment by excitoon** [comment] 2018-03-02 19:12
According equation.com, one can see that that guy has his own nameservers on ftp.equation.com and www.equation.com //_-. Most possibly, these servers are used virtually for everything (jserver, apache, nfs, mail, etc) and I don't think they are sustainable.

By the way, can we describe mirrors in manifests?

**Comment by Fleshgrinder** [comment] 2018-03-02 19:26
I fully agree it's a very bad user experience this way. We have to update the manifests manually anyways, why not simply add the binaries to this repo as well.

**Comment by excitoon** [comment] 2018-03-10 14:40
Just received one more error right on AppVeyor:
```
49 Installing 'make' (4.2) [64bit]
50 The remote server returned an error: (530) Not logged in.
51 URL ftp://ftp.equation.com/make/64/make.exe is not valid
```

It's bad from developer perspective too because that will cause builds to fail.

**Comment by excitoon** [comment] 2018-03-10 14:49
As a workaround I have a solution for 64-bit systems: https://github.com/excitoon/scoop-user/blob/master/make.json .

**Comment by rasa** [comment] 2018-03-10 14:58
While I appreciate statically complied tools, we could switch to http://repo.msys2.org/msys/x86_64/make-4.2.1-1-x86_64.pkg.tar.xz for a few reasons:
1. Download more trustworthy
2. Executable more trustworthy
3. Better chance of working with other msys tools
4. Pedictable updates 
I promised @r15ch13 I wouldn’t repackage more msys apps, but perphaps he’ll make an exception for broken apps.

**Comment by r15ch13** [comment] 2018-03-10 22:43
@rasa moving to a more reliable download is more important. 👍

**Comment by rasa** [comment] 2018-03-11 00:05
@r15ch13: @excitoon's has many great packages in https://github.com/excitoon/scoop-user/ that may want to live in the main bucket to provide the freshest apps, and more reliable downloads.

**Comment by Fleshgrinder** [comment] 2018-03-23 09:10
Tried the `make` from https://github.com/excitoon/scoop-user/ but it fails in git bash for me with the fatal error "cygheap base mismatch detected".

**Comment by rasa** [comment] 2018-03-23 13:30
@Fleshgrinder: well that’s bad news. I guess we’ll have to make sure to stay in sync with git-bash’s msys2 version.

**Comment by Fleshgrinder** [comment] 2018-03-23 16:14
Tried the http://repo.msys2.org/msys/x86_64/make-4.2.1-1-x86_64.pkg.tar.xz version and this one works out of the box. Maybe we can switch to this one?

**Comment by rasa** [comment] 2018-03-24 01:17
@Fleshgrinder weird, that’s the same as excitoon’s: https://github.com/excitoon/scoop-user/blob/master/make.json#L15

**Comment by excitoon** [comment] 2018-03-24 09:16
@Fleshgrinder did you install Git-Bash from scoop as well?

As I can guess the problem is Git-Bash spoils finding `cygwin1.dll` in scoop app directory. Possibly it can be solved by making some kind of enforced shim, which would not pass Git-Bash environment into the application.

**Comment by excitoon** [comment] 2018-03-24 09:18
I think we can't afford having the same versions of every DLL of every application in a repo and in sync with all external application.

**Comment by Fleshgrinder** [comment] 2018-04-14 09:25
@excitoon nope, did not install Git Bash via scoop on the machine I tested your make with. However, I noticed that the installation of your make also starts installing Bash and other stuff.

**Comment by rasa** [comment] 2020-10-21 01:42
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2076

**Closed by rasa** 2020-10-21 01:42 UTC
