### ISSUE TITLE
Cannot validate argument on parameter 'FilePath'

### ISSUE THREAD

**Issue by Egenet** [lukesampson/scoop#3922] opened 2020-04-09 15:14 UTC
> scoop install git
...
$Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa …
                                 ~~~~~~~
Cannot validate argument on parameter 'FilePath'

Which is quite reasonable because the '7z' folder is just empty. 

But!

> scoop install 7zip
Installing '7zip' (19.00) [64bit]
No connection could be made because the target machine actively refused it. No connection could be made because the target machine actively refused it.
URL https://7-zip.org/a/7z1900-x64.msi is not valid

**Comment by tan-wei** [comment] 2020-05-01 04:39
Please check your network and retry. I confirm that for now, the URL is valid.

**Comment by rasa** [comment] 2020-10-20 23:13
Duplicate of #3517

**Closed by rasa** 2020-10-20 23:13 UTC
