### ISSUE TITLE
making a formula to compile directly from the source code

### ISSUE THREAD

**Issue by Foadsf** [lukesampson/scoop#2404] opened 2018-07-19 07:00 UTC
I'm looking for a Windows package manager which can directly download the source code from the developers github repository. I asked the Chocolatey developers [here](https://github.com/chocolatey/chocolatey-package-requests/issues/376#), and apparently it can't handle that. Considering that Scoop is inspired by HomeBrew, I thought maybe Scoop might have the ability to do so. What I need is that the package manager have a script to install the dependencies and then download the source code from github repository and and compile and install it.

**Comment by Ash258** [comment] 2018-07-19 07:06
#340

**Comment by Foadsf** [comment] 2018-07-19 07:09
@Ash258 Thanks a lot and my apology for the duplicate. So I guess it is not possible at the moment? are you by any chance aware of [any Windows package manager](https://github.com/repology/repology/issues/658#) which can do this?

**Comment by rasa** [comment] 2020-10-20 21:55
Duplicate of #340

**Closed by rasa** 2020-10-20 21:55 UTC
