### ISSUE TITLE
Request: Add Zoom conferencing software

### ISSUE THREAD

**Issue by pcgeek86** [lukesampson/scoop#3957] opened 2020-05-02 00:03 UTC
If possible, it would be great to have Zoom conferencing software installable via scoop package manager.

https://zoom.us

Here's the documentation for Zoom deployment. They seem to recommend using the MSI installer, but I noticed that Scoop has deprecated this capability.

https://support.zoom.us/hc/en-us/articles/201362163-Mass-Installation-and-Configuration-for-Windows

**Comment by pcgeek86** [comment] 2020-05-02 00:27
I tried creating this, but ran into a few problems.

* `zoommtg` needs to be registered as a URL scheme, but isn't
* Zoom doesn't have proper icon in Start Menu, and doesn't provide an icon file separate from .exe file
* Zoom leaves a command window open, which must manually be closed

```json
{
    "version": "5.0.23502.430",
    "url": "https://www.zoom.us/client/latest/ZoomInstallerFull.msi",
    "bin": "Program Files Folder\\Zoom\\bin\\zoom.exe",
    "hash": "f4434eeec423cebfef82086eea33213ab565c3e59d6fd5fd553b66dcb86f2567",
    "shorcuts": [
        [
            "Program Files Folder\\Zoom\\bin\\zoom.exe",
            "Zoom",
            "",
            ""
        ]
    ]
}
```

Maybe someone else can fix this up for publication?

**Comment by Ash258** [comment] 2020-05-02 07:18
Duplicate of lukesampson/scoop-extras#3920

**Closed** 2020-05-02 16:13 UTC
