### ISSUE TITLE
ssh-keygen failing to create key pair

### ISSUE THREAD

**Issue by priya-acharya** [lukesampson/scoop#1593] opened 2017-07-12 11:24 UTC
Hi,

When i tried to create public-private key pair using openssh I got the following error.

Generating public/private rsa key pair.
Enter file in which to save the key (//.ssh/id_rsa):
Could not create directory '//.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
open //.ssh/id_rsa failed: No such host or network path.
Saving the key failed: //.ssh/id_rsa.

Expected Behaviour: 
It should have created id_rsa.pub and id_rsa files in .ssh folder.

**Comment by gheoan** [comment] 2017-07-14 17:57
Possible duplicate of https://github.com/lukesampson/scoop/issues/1449.

**Closed** 2018-03-12 19:25 UTC
