### ISSUE TITLE
[Extras] Add Ghidra support

### ISSUE THREAD

**Issue by T145** [lukesampson/scoop#3671] opened 2019-10-03 18:29 UTC
https://ghidra-sre.org/

**Comment by SonOfDiablo** [comment] 2019-10-04 08:16
If you want Ghidra as an app you can install from Scoop then you might want to suggest it over on the [Extras Bucket Repo](https://github.com/lukesampson/scoop-extras), make your own bucket or check out this [Bucket](https://github.com/TheCjw/scoop-retools) that is all about Reverse Engineering tools.

**Comment by r15ch13** [comment] 2019-10-04 19:25
Duplicate of https://github.com/lukesampson/scoop-extras/issues/1814

**Closed by r15ch13** 2019-10-04 19:25 UTC
