### ISSUE TITLE
Cannot install `less`

### ISSUE THREAD

**Issue by SebastienEGNER** [lukesampson/scoop#3614] opened 2019-08-28 16:34 UTC
Hello,

I tried to install `less` but the installation failed with the following error message:

```
Installing 'less' (551) [64bit]
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
URL https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z is not valid
```

I have no issues when I try other packages.

**Comment by rasa** [comment] 2019-08-29 01:58
Duplicate of https://github.com/ScoopInstaller/Main/issues/376

**Closed by rasa** 2019-08-29 01:58 UTC
