### ISSUE TITLE
LibreOffice install failed at extract

### ISSUE THREAD

**Issue by zaniar** [lukesampson/scoop#3940] opened 2020-04-24 13:22 UTC
Here is what I got

```
> scoop install libreoffice-fresh
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'libreoffice-fresh' (6.4.3.2) [64bit]
Loading LibreOffice_6.4.3.2_Win_x64.msi from cache.
Checking hash of LibreOffice_6.4.3.2_Win_x64.msi ... ok.
Extracting LibreOffice_6.4.3.2_Win_x64.msi ... Could not find 'LibreOffice'! (error 16)
At C:\Users\User\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'LibreOffice'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'LibreOffice'! (error 16)
```

**Comment by Ash258** [comment] 2020-04-24 13:24
Duplicate of lukesampson/scoop-extras#3869

**Closed** 2020-04-24 13:41 UTC
