### ISSUE TITLE
Listing aliases error

### ISSUE THREAD

**Issue by PrefixCoder** [lukesampson/scoop#4126] opened 2020-09-30 21:42 UTC
## Problem

Error message appears upon running `scoop alias list` 

## Message
```powershell
λ scoop alias list
Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-IsReadOnly.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...-IsReadOnly.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-IsReadOnly.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...-IsReadOnly.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-IsFixedSize.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...IsFixedSize.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-IsFixedSize.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...IsFixedSize.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-IsSynchronized.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...ynchronized.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-IsSynchronized.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...ynchronized.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-Keys.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...\scoop-Keys.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-Keys.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...\scoop-Keys.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-Values.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...coop-Values.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-Values.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...coop-Values.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-SyncRoot.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...op-SyncRoot.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-SyncRoot.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...op-SyncRoot.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-Count.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\lib\commands.ps1:22 char:19
+         $line = ((Get-Content $shim_path) | Where-Object { $_.startsw ...
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...scoop-Count.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Users\Winda\scoop\shims\scoop-Count.ps1' because it does not exist.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:91 char:20
+         $content = Get-Content (command_path $_.Name)
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Winda\...scoop-Count.ps1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:92 char:9
+         $command = ($content | Select-Object -Skip 1).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\Winda\scoop\apps\scoop\current\libexec\scoop-alias.ps1:93 char:9
+         $summary = (summary $content).Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull


Count
IsFixedSize
IsReadOnly
IsSynchronized
Keys
SyncRoot
Values
```

**Comment by Ash258** [comment] 2020-09-30 21:44
Duplicate of #3528, #4064

**Comment by rasa** [comment] 2020-10-20 21:58
Duplicate of #3528, #4064

**Closed by rasa** 2020-10-20 21:58 UTC
