### ISSUE TITLE
Error Installing Git

### ISSUE THREAD

**Issue by masonm12** [lukesampson/scoop#517] opened 2015-10-06 08:13 UTC
I get the following error when installing git, looks like it's failing the env_set step, which in turn causes git to use the wrong ssh.exe and fail to pick up on OpenSSH's ssh-agent. Git then proceeds to ask my passphrase all the time. Not a showstopper, but certainly undesirable. Tested plain ssh commands against ssh -T git@github.com, so it's just git fetch/push that seem to be affected.

    Exception calling "ExpandString" with "1" argument(s): "Object reference not set to an instance of an object."
    At C:\Users\Mathew\appdata\local\scoop\apps\scoop\current\lib\core.ps1:9 char:5
    +     $executionContext.invokeCommand.expandString($str)
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
        + FullyQualifiedErrorId : NullReferenceException
    
    running post-install script...

**Comment by mmcalli** [comment] 2015-10-08 22:45
+1 - having the same issue here.

**Comment by masonm12** [comment] 2015-10-08 23:12
To workaround for my setup I just put the following in my ps profile, which I assume is equivalent to what the manifest was trying to do.

    $env:GIT_SSH = "$(resolve-path $(scoop which ssh))"

**Comment by mathieucarbou** [comment] 2015-10-31 15:52
Have teh same error, the workaround does not work. I think issue and #529 are the same.

**Comment by deevus** [comment] 2016-01-08 23:22
Duplicate of #529

**Closed by deevus** 2016-01-08 23:22 UTC
Labels: duplicate
