### ISSUE TITLE
ccleaner install downloads 0 Bytes 7z file

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [lukesampson/scoop#2284] opened 2018-05-25 21:36 UTC
the error is 

```
scoop install ccleaner
Installing 'ccleaner' (5.43.6522) [64bit]
Downloading https://www.piriform.com/ccleaner/download/portable/downloadfile#/dl.7z (0 B)...

Checking hash of downloadfile... ok.
Extracting... ERROR: D:\xxxxxxxx\scoop\apps\ccleaner\5.43.6522\dl.7z
Can not open the file as archive

Exit code was 2.
```

Notice says 0 B file. The error makes sense because 7zip cannot open the archive because is an empty file.

I tried to follow that link and there is no file located at that url. I guess they removed the portable download.

**Comment by Ash258** [comment] 2018-05-25 22:42
Wrong bucket. 
Also duplicate of https://github.com/lukesampson/scoop-extras/issues/939

**Closed** 2018-05-26 07:41 UTC
