### ISSUE TITLE
GCC 

### ISSUE THREAD

**Issue by luokn** [lukesampson/scoop#4332] opened 2021-04-20 10:32 UTC
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

**Comment by dwettstein** [comment] 2021-04-23 08:16
Duplicate of https://github.com/lukesampson/scoop/issues/4277, https://github.com/lukesampson/scoop/issues/4250. More info here: https://github.com/ScoopInstaller/Main/issues/1752

**Comment by dwettstein** [comment] 2021-05-07 08:49
Relates https://github.com/lukesampson/scoop/issues/3990

**Closed** 2021-08-05 03:04 UTC
