### ISSUE TITLE
Unable to install vim on win 8.1

### ISSUE THREAD

**Issue by mr-moon** [lukesampson/scoop#278] opened 2015-02-08 07:32 UTC
This is what it get. Doesn't mater if I run as Admin or not.

```
system32 $ scoop install vim
installing vim (7.4)
loading http://ftp.vim.org/pub/vim/pc/vim74w32.zip from cache...
checking hash...ok
extracting...rm : Cannot remove item C:\Users\Alexander\appdata\local\scoop\apps
\vim\7.4\_sc
oop_extract\vim\vim74\install.exe: Access to the path is denied.
At C:\Users\Alexander\appdata\local\scoop\apps\scoop\current\lib\install.ps1:21
2 char:6
+                     rm -r -force "$dir\_scoop_extract" -ea stop
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (install.exe:FileInfo) [Remove-
   Item], ArgumentException
    + FullyQualifiedErrorId : RemoveFileSystemItemArgumentError,Microsoft.Powe
   rShell.Commands.RemoveItemCommand
```

**Comment by nightire** [comment] 2015-02-28 08:24
Same here... @mr-moon can you find a way to solve this?

**Comment by gutierri** [comment] 2015-03-11 03:50
Close?

**Comment by nightire** [comment] 2015-03-11 03:54
@gutierri not in my world

**Comment by lukesampson** [comment] 2015-03-11 03:58
Yeah let's not close it yet, I just can't reproduce the error.

@nightire can you show me your `$psversiontable`?

**Comment by nightire** [comment] 2015-03-11 04:01
@lukesampson sure, windows laptop is away from me right now, as soon as I get back to home, I will show what you need.

**Comment by deevus** [comment] 2015-04-07 02:15
@nightire How did you go with this?

**Comment by nightire** [comment] 2015-04-07 05:51
@lukesampson @deevus 

```
Name                                                                       Value
--------                                                                       --------
PSVersion                                                                4.0
WSManStackVersion                                               3.0
SerializationVersion                                                 1.1.0.1
CLRVersion                                                              4.0.30319.34014
BuildVersion                                                             6.3.9600.17090
PSCompatibleVersions                                            {1.0, 2.0, 3.0, 4.0}
PSRemotinProtocolVersion                                      2.2
```

OS: Windows 8.1

**Comment by sarbazx** [comment] 2015-04-29 15:36
uninstall vim then install vim again this worked for me :)

**Comment by deevus** [comment] 2015-05-04 06:53
Sorry @nightire I'm just not able to reproduce this. I would suggest that you reinstall scoop and give this another shot with a clean install.

**Closed by deevus** 2015-05-04 06:53 UTC
