### ISSUE TITLE
Scoop bucket update not processed?

### ISSUE THREAD

**Issue by watkinsmatthewp** [lukesampson/scoop#3644] opened 2019-09-17 15:57 UTC
I have installed IntelliJ-IDEA installed using the [jetbrains bucket](https://github.com/Ash258/Scoop-JetBrains). When I run `scoop update *` and `scoop cleanup *`, scoop tells me everything is up to date and everything is shiny now. Installed version is 2019.2-192.5728.98.

However, looking at the JetBrains bucket repo, I see that the version scoop thinks is latest was the version that was updated almost 2 months ago. There have been several version updates since then. The most recent change was 11 days ago to update to version 2019.2.2-192.6603.28.

Is the Scoop CLI caching the bucket info or something? How can I get it to actually get the latest version of the app?

### Steps to reproduce

1. Add the jetbrains bucket
1. Install IntelliJ-IDEA
1. Wait for the bucket owner to update IntelliJ-IDEA.json
1.  `scoop update IntelliJ-IDEA`

**Comment by Ash258** [comment] 2019-09-17 15:59
Duplicate of #3329 #2981 #2720

Fixed by #3333 already in develop branch

**Closed** 2019-10-18 13:03 UTC
