### ISSUE TITLE
exiftool fails to install; stops installing other packages

### ISSUE THREAD

**Issue by alejandro5042** [lukesampson/scoop#2081] opened 2018-03-03 00:03 UTC
```
> scoop uninstall exiftool; scoop install exiftool zstd
Uninstalling 'exiftool' (10.82).
'exiftool' was uninstalled.
Installing 'exiftool' (10.82) [64bit]
Loading exiftool-10.82.zip from cache
Checking hash of exiftool-10.82.zip... ok.
Extracting... Unzip failed: Exception calling "ExtractToDirectory" with "2" argument(s): "End of Central Directory record could not be found."
````

When exiftool fails, it throws this exception.

Here's a trace:

```
DEBUG:  455+     return  >>>> $true
DEBUG:  456+  >>>> }
DEBUG:     ! SET $ok = 'True'.
DEBUG:     ! SET $err = ''.
DEBUG:  314+             if( >>>> !$ok) {
DEBUG:  322+          >>>> $extract_dir = $extract_dirs[$extracted]
DEBUG:     ! SET $extract_dir = ''.
DEBUG:  323+          >>>> $extract_to = $extract_tos[$extracted]
DEBUG:     ! SET $extract_to = ''.
DEBUG:  326+          >>>> $extract_fn = $null
DEBUG:     ! SET $extract_fn = ''.
DEBUG:  327+         if( >>>> $fname -match '\.zip$') { # unzip
DEBUG:  328+              >>>> $extract_fn = 'unzip'
DEBUG:     ! SET $extract_fn = 'unzip'.
DEBUG:  351+         if( >>>> $extract_fn) {
DEBUG:  352+              >>>> write-host "Extracting... " -nonewline
Extracting... DEBUG:  353+              >>>> $null = mkdir "$dir\_tmp"
DEBUG:  377+     'mkdir' =  >>>> { new-item -type directory @args }
DEBUG:     ! CALL function '<ScriptBlock>'  (defined in file 'C:\Users\abarreto\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:  377+     'mkdir' = {  >>>> new-item -type directory @args }
DEBUG:  377+     'mkdir' = { new-item -type directory @args  >>>> }
DEBUG:  354+              >>>> & $extract_fn "$dir\$fname" "$dir\_tmp"
DEBUG:  167+ function unzip($path,$to)  >>>> {
DEBUG:     ! CALL function 'unzip'  (defined in file 'C:\Users\abarreto\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:  168+     if( >>>> !(test-path $path)) { abort "can't find $path to unzip"}
DEBUG:  169+     try {  >>>> add-type -assembly "System.IO.Compression.FileSystem" -ea stop }
DEBUG:  172+          >>>> [io.compression.zipfile]::extracttodirectory($path,$to)
DEBUG:  182+          >>>> abort "Unzip failed: $_"
DEBUG:   42+ function abort($msg, [int] $exit_code=1)  >>>> { write-host $msg -f red; exit $exit_code }
DEBUG:     ! CALL function 'abort'  (defined in file 'C:\Users\abarreto\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:   42+ function abort($msg, [int] $exit_code=1) {  >>>> write-host $msg -f red; exit $exit_code }
Unzip failed: Exception calling "ExtractToDirectory" with "2" argument(s): "End of Central Directory record could not be found."
```

Also when it fails, it does not continue installing the next package, `zstd` in this example. This is annoying because I have a script that ensures that 20-ish packages are installed on the machine, and it stops on any error. The only way to keep going is to call `scoop install` on each one, but that's MUCH slower.

I also propose there be a `--force, -f` option to uninstall the package and then install it, to avoid the uninstall and install step I am doing.

**Comment by rasa** [comment] 2018-03-13 00:25
Thanks for the detailed report, but this is essentially a duplicate of #1864.

**Closed by rasa** 2018-03-13 00:25 UTC
